### PR TITLE
Fixed styling issue on the movement page

### PR DESCRIPTION
**Pull request by lmdagency**
@webb, can you please re-pull and merge this version. We found a styling issue and fixed it. Thanks

### CODE REVIEW

**Comment by webb** [comment]
Please merge niem/master into your branch first.

**Comment by lmdagency** [comment]
Master is merged and conflict is resolved.

**Comment by webb** [comment]
Thanks! Done

**Comment by lmdagency** [comment]
Not sure if the sass build is taking its time, but the CSS change hasn't taken effect yet.

**Comment by lmdagency** [comment]
It is working now. Thanks

**Pull request merged**
